#!/usr/bin/env node
/**
 * Generates the pitch transcript with chapter timestamps.
 *
 * Written from `manifest.json` and `narration.json` using the same timing module
 * the renderer uses, so the transcript is produced without re-rendering a
 * five-minute video — and still reports where each chapter actually begins.
 * `verify-video.mjs` cross-checks the total against the rendered file, which is
 * what stops the two from silently drifting apart.
 *
 * Output: `out/TRANSCRIPT.md`, linked from the README.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { scenes } from './scenes.mjs';
import { sceneTiming } from './timing.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'out');

/** `m:ss`, matching the runtime format shown in the README. */
function timestamp(seconds) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, '0')}`;
}

function main() {
  // The spoken text is read from `scenes.mjs`, not from `manifest.json`.
  //
  // The manifest is a capture-time artifact: it records the narration as it was
  // when the screenshots were taken. Editing the script afterwards leaves it
  // stale, and a transcript built from it silently omits whatever was added —
  // while the audio, which is regenerated from `scenes.mjs`, has it. The script
  // is the single source of truth for what is said; only the timing comes from
  // the recorded narration.
  const narration = JSON.parse(readFileSync(join(HERE, 'narration.json'), 'utf8'));
  const narrationById = new Map(narration.scenes.map((s) => [s.id, s]));

  const chapters = [];
  let elapsed = 0;

  for (const scene of scenes) {
    const entry = narrationById.get(scene.id);
    if (!entry) throw new Error(`no narration recorded for scene ${scene.id}; run narrate.mjs first`);
    if (!scene.shots.length) throw new Error(`scene ${scene.id} has no shots`);

    const { seconds } = sceneTiming(scene.shots.length, entry.audioSeconds);
    chapters.push({ start: elapsed, title: scene.title, narration: scene.narration });
    elapsed += seconds;
  }

  const lines = [
    '# LumenMint pitch — transcript',
    '',
    `Spoken narration of [the product pitch](./stellar-lumenmint-pitch.mp4) ` +
      `(${timestamp(elapsed)}, ${chapters.length} chapters). Generated by ` +
      '`npm run transcript` from `scenes.mjs` — edit the script there, not this file.',
    '',
    `**Chapters:** ${chapters.map((c) => `${timestamp(c.start)} ${c.title}`).join(' · ')}`,
    '',
  ];

  for (const chapter of chapters) {
    lines.push(`## [${timestamp(chapter.start)}] ${chapter.title}`, '');
    // Quoted per line so chapters stay visually separated; a bare paragraph
    // would run straight into the next heading.
    lines.push(...chapter.narration.split('\n').map((line) => `> ${line}`), '');
  }

  writeFileSync(join(OUT, 'TRANSCRIPT.md'), lines.join('\n'));
  console.log(`  transcript  out/TRANSCRIPT.md  ${chapters.length} chapters, ${timestamp(elapsed)}`);
}

main();
